### PR TITLE
do not install in production mode

### PR DESCRIPTION
**Pull request by zhaoyao91**
devDependencies will not be installed with --production.

### CODE REVIEW

**Comment by zhaoyao91** [comment]
devDependencies will not be installed with --production.

**Comment by cluxter** [comment]
`--production` is not intended for production.

**Comment by laosb** [comment]
@zhaoyao91 I'm really avoiding devDependencies by using `--production`. Is there any specific reason to have devDeps in a production app?

@cluxter It's npm's `--production` which is used to avoid devDeps, not the Meteor one.

**Comment by zhaoyao91** [comment]
image

**Comment by laosb** [comment]
Ah, I see.

**Comment by laosb** [comment]
I guess this is safe.

**Pull request merged**
